INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Cemol 500 ml (ยาลดไข้ แก้ปวดระดับต้น)','35','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Panadol (ยาลดไข้ แก้ปวดระดับต้น)','39','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Paracap 500 ml (ยาลดไข้ แก้ปวดระดับต้น)','50','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Sara 500 ml (ยาลดไข้ แก้ปวดระดับต้น)','100','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Tylenol 500 ml (ยาลดไข้ แก้ปวดระดับต้น)','100','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Tylenol (ยาลดไข้ แก้ปวดระดับต้น)','10','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Coprofen (ยาลดไข้ แก้ปวดระดับต้น)','20','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Sara (ยาลดไข้ แก้ปวดระดับต้น)','10','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Anadol (ยาแก้ปวด ระดับกลาง ถึง รุนแรง)','100','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Amanda (ยาแก้ปวด ระดับกลาง ถึง รุนแรง)','100','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Tramadol (ยาแก้ปวด) (ยาแก้ปวด ระดับกลาง ถึง รุนแรง)','100','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Cerazette (ยาคุมกำเนิด)','230','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Exluton (ยาคุมกำเนิด)','100','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Postinor (ยาคุมฉุกเฉิน)','40','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Madonna (ยาคุมฉุกเฉิน)','30','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาธาตุน้ำขาวไทยนคร 200 ml','55','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาธาตุน้ำขาวสหการ 200 ml','35','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาธาตุน้ำขาวตรากระต่ายบิน 50 ml','15','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Dimenhydrinate (ยาแก้แพ้ เมารถ คลื่นไส้)','10','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Denim (ยาแก้แพ้ เมารถ คลื่นไส้)','10','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาคลอเฟนิรามีน (ยาแก้แพ้ ลมพิษ ผื่นคัน)','50','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('เบลสิด ฟอร์ท 240 ml','50','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Antacil 240 ml','45','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ENO รสมะนาว','12','1000','ซอง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ENO รสส้ม','12','1000','ซอง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('แอนตาซิน','10','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Royal-D (รสส้ม)','12','1000','ซอง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Oreda (รสส้ม)','10','1000','ซอง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาแก้ไอน้ำดำตราเสือดาว','80','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('แอมโมเนีย 30 ml','15','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Ponstan 500','20','1000','แผง');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาใส่แผลเบนตาดีน 30 ml','20','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ทิงเจอร์ไอดีน','50','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('แอลกอฮอล์ 70% 30 ml','15','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('แอลกอฮอล์ 70% 60 ml','20','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('แอลกอฮอล์ 70% 240 ml','48','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('แอลกอฮอล์ 70% 450  ml','80','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('น้ำเกลือ Klean&Kare 500 ml','50','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('เบอร์นี่ เจล รักษาแผลไฟไหม้ น้ำร้อนลวก','50','1000','หลอด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Hiruscar','150','1000','หลอด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Hirudoid','80','1000','หลอด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาหม่องชนิดขี้ผึ้ง แซม-บัค','46','1000','ตลับ');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('ยาหม่อง ตราถ้วยทอง','35','1000','กระปุก');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('Calamine คาลาไมน์ ตราเสือดาว 60 ml','41','1000','ขวด');
INSERT INTO products(`pro_name`,`saleprice`,`stock_ps`,`contain`) VALUES ('pro_name','saleprice','stock_ps','contain');
